# Generated by Django 4.0.5 on 2022-07-12 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.TextField(default=datetime.datetime(2022, 7, 12, 7, 9, 39, 359494, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
